config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),

    #User Management
    path('accounts/', include('allauth.urls')),

    #local apps
    path('', include('videos.urls')),
]

users/urls.py
from django.urls import path

from .views import SignupPageView

urlpatterns = [
    path('signup/', SignupPageView.as_view(), name='signup'),
]

videos/urls.py
from django.urls import path
from .views import HomePageView, ThemeCreateView, DashboardView, ThemeDetailView, ThemeUpdateView, ThemeDeleteView, AddVideoView, VideoSearchView, VideoDeleteView

urlpatterns = [
    path('', HomePageView, name='home'),
    path('dashboard/', DashboardView, name='dashboard'),
    path('themes/create/', ThemeCreateView.as_view(), name='create_theme'),
    path('themes/<int:pk>', ThemeDetailView.as_view(), name='detail_theme'),
    path('themes/<int:pk>/update/', ThemeUpdateView.as_view(), name='update_theme'),
    path('themes/<int:pk>/delete/', ThemeDeleteView.as_view(), name='delete_theme'),
    path('themes/<int:pk>/addvideo/', AddVideoView, name='add_video'),
    path('video/search/', VideoSearchView, name='video_search'),
    path('video/<int:pk>/delete/', VideoDeleteView.as_view(), name='delete_video'),
]

users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models

# Create your models here.

class CustomUser(AbstractUser):
    pass

videos/models.py
from django.db import models
from django.contrib.auth import get_user_model

class Theme(models.Model):
    title = models.CharField(max_length=100)
    user = models.ForeignKey(get_user_model(), on_delete=models.CASCADE)

    def __str__(self):
        return self.title

class Video(models.Model):
    title = models.CharField(max_length=250)
    url = models.URLField()
    youtube_id = models.CharField(max_length=250)
    theme = models.ForeignKey(Theme, on_delete=models.CASCADE)

    def __str__(self):
        return self.title

users/forms.py
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm, UserChangeForm

class CustomUserCreationForm(UserCreationForm):

    class Meta:
        model = get_user_model()
        fields = ('email', 'username',)


class CustomUserChangeForm(UserChangeForm):

    class Meta:
        model = get_user_model()
        fields = ('email', 'username',)

videos/forms.py
from .models import Video
from django import forms

class VideoForm(forms.ModelForm):
    class Meta:
        model = Video
        fields = ['url']
        labels = {'url':'YouTube URL'}

class SearchForm(forms.Form):
    search_term = forms.CharField(max_length=100, label='Search for videos (just type and wait, do not press enter!):')

users/views.py
from django.urls import reverse_lazy
from django.views import generic

from .forms import CustomUserCreationForm

class SignupPageView(generic.CreateView):
    form_class = CustomUserCreationForm
    success_url = reverse_lazy('login')
    template_name = 'signup.html'

videos/views.py
from django.shortcuts import render, redirect
from django.shortcuts import redirect
from django.urls import reverse_lazy
from django.views.generic import TemplateView, CreateView, DetailView, UpdateView, DeleteView
from .models import Theme, Video
from .forms import VideoForm, SearchForm
from django.http import Http404, JsonResponse
from django.forms.utils import ErrorList
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
import urllib
import requests
import os

YOUTUBE_API_KEY = os.environ.get('YOUTUBE_API_KEY')

def HomePageView(request):
    recent_themes = Theme.objects.all().order_by('-id')[:3]
    return render(request, 'home.html', {'recent_themes':recent_themes})

@login_required
def DashboardView(request):
    themes = Theme.objects.filter(user=request.user)
    return render(request, 'dashboard.html', {'themes':themes})

class ThemeCreateView(LoginRequiredMixin, CreateView):
    model = Theme
    fields = ['title']
    template_name = 'create_theme.html'
    success_url = reverse_lazy('dashboard')

    def form_valid(self, form):
        form.instance.user = self.request.user
        super(ThemeCreateView, self).form_valid(form)
        return redirect('dashboard')

class ThemeDetailView(DetailView):
    model = Theme
    template_name = 'detail_theme.html'

class ThemeUpdateView(LoginRequiredMixin, UpdateView):
    model = Theme
    fields = ['title']
    template_name = 'update_theme.html'
    success_url = reverse_lazy('dashboard')

    def get_object(self):
        theme = super(ThemeUpdateView, self).get_object()
        if not theme.user == self.request.user:
            raise Http404
        return theme

class ThemeDeleteView(LoginRequiredMixin, DeleteView):
    model = Theme
    template_name = 'delete_theme.html'
    success_url = reverse_lazy('dashboard')

    def get_object(self):
        theme = super(ThemeDeleteView, self).get_object()
        if not theme.user == self.request.user:
            raise Http404
        return theme

@login_required
def AddVideoView(request, pk):
    form = VideoForm()
    search_form = SearchForm()
    theme = Theme.objects.get(pk=pk)
    if not theme.user == request.user:
        raise Http404

    if request.method == 'POST':
        form = VideoForm(request.POST)
        if form.is_valid():
            video = Video()
            video.theme = theme
            video.url = form.cleaned_data['url']
            parsed_url = urllib.parse.urlparse(video.url)
            video_id = urllib.parse.parse_qs(parsed_url.query).get('v')

            if video_id:
                video.youtube_id = video_id[0]
                response = requests.get(f'https://youtube.googleapis.com/youtube/v3/videos?part=snippet&id={video_id[0]}&key={YOUTUBE_API_KEY}')
                json = response.json()
                title = json['items'][0]['snippet']['title']
                video.title = title
                video.save()
                return redirect('detail_theme', pk)
            else:
                errors = form._errors.setdefault('url', ErrorList())
                errors.append('Please use a YouTube URL')

    return render(request, 'add_video.html', {'form':form, 'search_form':search_form, 'theme':theme})

@login_required
def VideoSearchView(request):
            search_form = SearchForm(request.GET)
            if search_form.is_valid():
                encoded_search_term = urllib.parse.quote(search_form.cleaned_data['search_term'])
                response = requests.get(f'https://www.googleapis.com/youtube/v3/search?part=snippet&maxResults=6&q={ encoded_search_term }&key={ YOUTUBE_API_KEY }')
                return JsonResponse(response.json())
            return JsonResponse({'error':'Not able to validate form'})

class VideoDeleteView(LoginRequiredMixin, DeleteView):
    model = Video
    template_name = 'delete_video.html'
    success_url = reverse_lazy('dashboard')

    def get_object(self):
        video = super(VideoDeleteView, self).get_object()
        if not video.theme.user == self.request.user:
            raise Http404
        return video

templates/add_video.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}
<div class="container">

<h2>Add a video to your Theme {{ theme.title }}</h2>
<form method="post" id="submit_video">
  {% csrf_token %}
  {{ form|crispy }}
  <button class="btn btn-primary" type="submit">Add</button>
</form>

<br>

<a href="{% url 'dashboard' %}" class="btn btn-secondary" >Cancel</a>

<br><br>

<h2>Or</h2>
<form method="post">
  {% csrf_token %}
  {{ search_form|crispy }}
</form>

<div id="search_results"></div>
<script>
  var delayTimer;
  $('#id_search_term').keyup(function() {
    clearTimeout(delayTimer);
    $('#search_results').text('Loading...');
    delayTimer = setTimeout(function() {
      var text = $('#id_search_term').val();
      $.ajax({
        url: '/video/search',
        data: {
          'search_term': text
        },
        dataType: 'json',
        success: function(data) {
          var results = '';
          $('#search_results').text('');
          results += '<div class="row">';
          data['items'].forEach(function(video) {
            results += '<div class="col-md-4 mt-3"><div class="card mb-4 shadow-sm h-100">';
            results += '<iframe width="100%" height="225" src="https://www.youtube.com/embed/' + video['id']['videoId'] +
              '" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>';
            results += '<div class="card-body"><p class="card-text">' + video['snippet']['title'] + '</p>';
            results += '<a href="#" class="btn btn-primary" onclick="addVideo(\'' + video['id']['videoId'] + '\')">Add</a></div></div></div>';

          });
          results += '</div>';
          $('#search_results').append(results);
        }
      });
    }, 1000);
  });

  function addVideo(video_id) {
    $('#id_url').val('https://www.youtube.com/watch?v=' + video_id);
    $('#submit_video').submit();
  }
</script>
</div>

{% endblock content %}

templates/base.html
<!doctype html>
<html lang="en">
{% load static %}

<head>
  <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BmbxuPwQa2lc/FVzBcNJ7UAyJxM6wuqIj61tLrc4wSX0szH/Ev+nYRRuWlolflfl" crossorigin="anonymous">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css" integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous">
    <link href="{% static 'css/custom.css' %}" rel="stylesheet">
    <link rel="shortcut icon" type="image/png" href="{% static 'images/favicon.ICO' %}" />
    <title>Video Sharing</title>
</head>

<body>
  <div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 bg-white border-bottom shadow-sm">
    <h5 class="my-0 mr-md-auto font-weight-normal"><a href="{% url 'home' %}" class="text-dark">Home</a></h5>
    <nav class="my-2 my-md-0 mr-md-3">
      {% if user.is_authenticated %}
      <a class="p-2 text-dark" href="{% url 'dashboard' %}">Dashboard</a>
      <a class="p-2 text-dark" href="{% url 'account_logout' %}">Log Out</a>
      {% else %}
      <a class="p-2 text-dark" href="{% url 'account_login' %}">Log In</a>
      {% endif %}
    </nav>
    {% if user.is_authenticated == False %}
    <a class="btn btn-outline-primary" href="{% url 'account_signup' %}">Sign up</a>
    {% endif %}
  </div>

  <br><br>

  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.6.0/dist/umd/popper.min.js" integrity="sha384-KsvD1yqQ1/1+IA7gi3P0tyJcT3vR+NdBTt13hSJ2lnve8agRGXTTyNaBYmCR/Nwi" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/js/bootstrap.min.js" integrity="sha384-nsg8ua9HAw1y0W1btsyWgBklPnCUAFLuTMS2G72MMONqmOymq585AcH49TLBQObG" crossorigin="anonymous"></script>

    {% block content %}

    {% endblock %}

</body>

</html>

templates/create_theme.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}
<div class="container">

<h2>Create a new Theme for your videos</h2>
<form method="post">
  {% csrf_token %}
  {{ form|crispy }}
  <button class="btn btn-primary" type="submit">Create Theme</button>
</form>

<br>

<a href="{% url 'dashboard' %}" class="btn btn-secondary" >Cancel</a>
</div>

{% endblock content %}

templates/dashboard.html
{% extends 'base.html' %}

{% block content %}

<div class="container">
  <div class="text-center">
    <h1>{{ user.username }}'s Video Themes</h1>
    <a href="{% url 'create_theme' %}" class="btn btn-primary">Create New Theme</a>
  </div>

    {% for theme in themes %}

<h2><a href="{% url 'detail_theme' theme.id %}">{{ theme.title }}</a></h2>

<a href="{% url 'update_theme' theme.id %}" class="btn btn-primary">Edit Theme</a>
<a href="{% url 'add_video' theme.id %}" class="btn btn-primary">Add Video</a>
<a href="{% url 'delete_theme' theme.id %}" class="btn btn-danger">Delete Theme</a>

    <div class="row">
      {% for video in theme.video_set.all %}
      <div class="col-md-4 mt-3">
        <div class="card mb-4 shadow-sm">
          <iframe width="100%" height="225" src="https://www.youtube.com/embed/{{ video.youtube_id }}" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
          <div class="card-body">
            <p class="card-text">{{ video.title }}</p>
          </div>
        </div>
      </div>
      {% endfor %}
      </div>


    {% endfor %}

</div>

{% endblock %}

templates/delete_theme.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}
<div class="container">

<h3>Are you sure you want to delete your Theme {{ theme.title }}?</h3>
<form method="post">
  {% csrf_token %}
  {{ form|crispy }}
  <button class="btn btn-danger" type="submit">Delete</button>
</form>

<br>

<a href="{% url 'dashboard' %}" class="btn btn-secondary" >Cancel</a>

</div>

{% endblock content %}

templates/delete_video.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}
<div class="container">
<h3>Are you sure you want to delete the video {{ video.title }}?</h3>
<form method="post">
  {% csrf_token %}
  {{ form|crispy }}
  <button class="btn btn-danger" type="submit">Delete</button>
</form>

<br>

<a href="{% url 'dashboard' %}" class="btn btn-secondary" >Cancel</a>

<br>

<div class="row">
  <div class="col-md-4 mt-3">
    <div class="card mb-4 shadow-sm">
      <iframe width="100%" height="225" src="https://www.youtube.com/embed/{{ video.youtube_id }}" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
      <div class="card-body">
        <p class="card-text">{{ video.title }}</p>
      </div>
    </div>
  </div>
</div>

</div>

{% endblock content %}

templates/detail_theme.html
{% extends 'base.html' %}

{% block content %}

<div class="container">

<div class="text-center">

<h2>{{ theme.title }}</h2>
<h4 class="text-muted">{{ theme.user.username }}</h4>

{% if user.id == theme.user.id %}
  <a href="{% url 'update_theme' theme.id %}" class="btn btn-primary">Edit Theme</a>
  <a href="{% url 'add_video' theme.id %}" class="btn btn-primary">Add Video</a>
  <a href="{% url 'delete_theme' theme.id %}" class="btn btn-danger">Delete Theme</a>
{% endif %}

</div>

<br>

    <div class="row">
      {% for video in theme.video_set.all %}
      <div class="col-md-4 mt-3">
        <div class="card mb-4 shadow-sm">
          <iframe width="100%" height="225" src="https://www.youtube.com/embed/{{ video.youtube_id }}" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
          <div class="card-body">
            <p class="card-text">{{ video.title }}</p>
            {% if user.id == theme.user.id %}
            <a href="{% url 'delete_video' video.id %}" class="btn btn-danger">Delete Video</a>
            {% endif %}
          </div>
        </div>
      </div>
      {% endfor %}
      </div>

</div>

{% endblock content %}

templates/home.html
{% extends 'base.html' %}

{% block content %}
<section class="jumbotron text-center">
  <div class="container">
    <h1 class="jumbotron-heading">Share your favorite Videos with the World!</h1>
    <p class="lead text-muted">Create video themes and add your favorite YouTube videos.</p>
    <p>
      <a href="{% url 'create_theme' %}" class="btn btn-primary">Get Started</a>
    </p>
  </div>
</section>
<div class="container">
  <h1 class="text-center">Recent Video Themes</h1>
  {% for theme in recent_themes %}

<h2><a href="{% url 'detail_theme' theme.id %}">{{ theme.title }}</a></h2>

  <div class="row">
    {% for video in theme.video_set.all %}
    <div class="col-md-4 mt-3">
      <div class="card mb-4 shadow-sm">
        <iframe width="100%" height="225" src="https://www.youtube.com/embed/{{ video.youtube_id }}" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
        <div class="card-body">
          <p class="card-text">{{ video.title }}</p>
        </div>
      </div>
    </div>
    {% endfor %}
    </div>
  {% endfor %}

</div>

{% endblock %}

templates/update_theme.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}

<div class="container">



<h2>Edit your existing Theme {{ theme.title }}</h2>
<form method="post">
  {% csrf_token %}
  {{ form|crispy }}
  <button class="btn btn-primary" type="submit">Edit</button>
</form>

<br>

<a href="{% url 'dashboard' %}" class="btn btn-secondary" >Cancel</a>

</div>

{% endblock content %}